package chat.client;

import chat.net.ClientThread;
import chat.server.Server;

import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Главное окно чата
 *
 * @author RKashaev
 */
public class ChatForm extends javax.swing.JFrame {
    // ссылка на поток для общения с сервером
    public ClientThread chatThread;
    // ссылка на окно логина
    public LoginDialog loginDialog;
    // имя пользователя
    private String userName;

    /**
     * Конструктор главной формы, где все происходит
     */
    public ChatForm() {
        initComponents();
        // для центрирования окна
        setLocationRelativeTo(null);
        // назначим кнопку по умолчанию
        getRootPane().setDefaultButton(buttonSend);
        // и поле
        tfText.requestFocus();
        loginDialog = new LoginDialog(this, true);
        // для центрирования диалога
        loginDialog.setLocationRelativeTo(this);
        // отображаем диалог
        loginDialog.setVisible(true);
        // если нажали Вход, то работаем, иначе программа выйдет
        try {
            String ipAddress = loginDialog.tfIP.getText();
            userName = loginDialog.tfLogin.getText();
            labelName.setText(userName);
            System.out.printf("%s: подключаемся к %s:%d...\n", userName, ipAddress, Server.PORT);
            // подключаемся к заданному IP-адресу и порту
            Socket socket = new Socket(ipAddress, Server.PORT);

            System.out.println("Соединение установлено");
            chatThread = new ClientThread(userName, socket, this);
            // отправляем сообщение о входе на сервер
            chatThread.sendConnect();
            // теперь запускаем поток слушать события сервера
            chatThread.start();
        } catch (IOException ex) {
            Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfChat = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Чат v1.0");

        tfChat.setEditable(false);
        jScrollPane1.setViewportView(tfChat);

        jLabel1.setText("Сообщения чата:");

        labelName.setText("Имя");

        buttonSend.setText("Отправить");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfText, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addComponent(tfText))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        String msg = tfText.getText().trim();
        if (msg.isEmpty()) {
            return;
        }
        // отправляем сообщение
        chatThread.sendMessage(userName, msg);
        tfText.setText("");
    }//GEN-LAST:event_buttonSendActionPerformed

    public void println(String message) {
        System.out.println(message);
        // выводим сообщение в окне чата
        Document doc = tfChat.getDocument();
        try {
            doc.insertString(doc.getLength(), message + "\n", null);
            tfChat.setCaretPosition(doc.getLength());
        } catch (BadLocationException ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // создаем окно чата
        ChatForm cf = new ChatForm();
        // отображаем
        cf.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelName;
    private javax.swing.JEditorPane tfChat;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
}
